Platform\DBBundle\Entity\personincharge:
    type: entity
    table: null
    repositoryClass: Platform\DBBundle\Repository\personinchargeRepository
    id:
        idpersonincharge:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        namepersonincharge:
            type: string
            length: '255'
        firstnamepersonincharge:
            type: string
            length: '255'
        mailpersonincharge:
            type: string
            length: '255'
            unique: true
        phonepersonincharge:
            type: string
            length: '10'
    lifecycleCallbacks: {  }
