Platform\DBBundle\Entity\subject:
    type: entity
    table: null
    repositoryClass: Platform\DBBundle\Repository\subjectRepository
    id:
        idsubject:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        subjectnumber:
            type: integer
        sexe:
            type: integer
        bornyear:
            type: integer
        postalcode:
            type: integer
        creationdate:
            type: datetime
        status:
            type: boolean
        commentary:
            type: text
    manyToOne:
        idinstitution:
            targetEntity: institution
            joinColumn:
                name: idinstitution
                referencedColumnName: idinstitution
    lifecycleCallbacks: {  }