platform_db:
    resource: "@PlatformDBBundle/Resources/config/routing.yml"
    prefix:   /

platform_user:
    resource: "@PlatformUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
