imports:
    - { resource: "@PlatformUserBundle/Resources/config/security.yml" }

# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
# app/config/security.yml

security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/subjects, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
