Platform\DBBundle\Entity\institution:
    type: entity
    table: null
    repositoryClass: Platform\DBBundle\Repository\institutionRepository
    id:
        idinstitution:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nameinstitution:
            type: string
            length: '255'
        adressinstitution:
            type: string
            length: '255'
            unique: true
        phoneinstitution:
            type: string
            length: '10'
    lifecycleCallbacks: {  }
