Platform\DBBundle\Entity\survey:
    type: entity
    table: null
    repositoryClass: Platform\DBBundle\Repository\surveyRepository
    id:
        idsurvey:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        commentary:
            type: text
            nullable: true
        datesurvey:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        idsubject:
            targetEntity: subject
            joinColumn:
                name: idsubject
                referencedColumnName: idsubject
                nullable: false
    lifecycleCallbacks: {  }