<?php

namespace Platform\DBBundle\Repository;

/**
 * personinchargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personinchargeRepository extends \Doctrine\ORM\EntityRepository
{
}
