<?php

namespace Platform\DBBundle\Repository;

/**
 * workshopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workshopRepository extends \Doctrine\ORM\EntityRepository
{
}
