<?php

namespace Platform\DBBundle\Repository;

/**
 * institutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class institutionRepository extends \Doctrine\ORM\EntityRepository
{
}
