<?php

namespace Platform\DBBundle\Repository;

/**
 * surveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class surveyRepository extends \Doctrine\ORM\EntityRepository
{
}
