<?php

namespace Platform\DBBundle\Repository;

/**
 * workshopsubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workshopsubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
